name: imgix
description: An Imgix library for Dart. Generate Imgix URLs with options easily
version: 0.2.0
homepage: https://github.com/Cretezy/imgix.dart

dependencies:
  meta: ^1.0.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  test: ^1.24.1
