name: imgix
description: An Imgix library for Dart. Generate Imgix URLs with options easily
version: 0.1.2
homepage: https://github.com/Cretezy/imgix.dart
author: Charles Crete <charles@cretezy.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
